sudo: required
services:
  - docker
before_install:
  - docker build -t aberger7/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aberger7/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dokcerreact-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-929684321701"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"